/* Generated by Cython 0.28.3 */

#ifndef __PYX_HAVE__gpd_lite_toolbox__cycartogram
#define __PYX_HAVE__gpd_lite_toolbox__cycartogram

struct Holder;
typedef struct Holder Holder;

/* "gpd_lite_toolbox/cycartogram.pyx":75
 * 
 * 
 * ctypedef public struct Holder:             # <<<<<<<<<<<<<<
 *     unsigned int lFID
 *     double ptCenter_x
 */
struct Holder {
  unsigned int lFID;
  double ptCenter_x;
  double ptCenter_y;
  double dValue;
  double dArea;
  double dMass;
  double dRadius;
};

#ifndef __PYX_HAVE_API__gpd_lite_toolbox__cycartogram

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

#endif /* !__PYX_HAVE_API__gpd_lite_toolbox__cycartogram */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initcycartogram(void);
#else
PyMODINIT_FUNC PyInit_cycartogram(void);
#endif

#endif /* !__PYX_HAVE__gpd_lite_toolbox__cycartogram */
